"""
Seed list of universities and their program pages for scraping.
Each entry contains the university name, country, and URL to scrape.
Updated with all universities from the programs list (165+ programs).
"""

UNIVERSITY_SEEDS = [
    # USA (39 universities)
    {"name": "MIT", "country": "USA", "city": "Cambridge, MA", "programs_page_url": "https://www.eecs.mit.edu/", "type": "robotics"},
    {"name": "Stanford University", "country": "USA", "city": "Stanford, CA", "programs_page_url": "https://cs.stanford.edu/", "type": "ai"},
    {"name": "Carnegie Mellon University", "country": "USA", "city": "Pittsburgh, PA", "programs_page_url": "https://www.ri.cmu.edu/", "type": "robotics"},
    {"name": "UC Berkeley", "country": "USA", "city": "Berkeley, CA", "programs_page_url": "https://eecs.berkeley.edu/", "type": "both"},
    {"name": "Caltech", "country": "USA", "city": "Pasadena, CA", "programs_page_url": "https://www.caltech.edu/", "type": "robotics"},
    {"name": "University of Michigan", "country": "USA", "city": "Ann Arbor, MI", "programs_page_url": "https://robotics.umich.edu/", "type": "robotics"},
    {"name": "Georgia Tech", "country": "USA", "city": "Atlanta, GA", "programs_page_url": "https://www.cc.gatech.edu/", "type": "both"},
    {"name": "University of Illinois Urbana-Champaign", "country": "USA", "city": "Urbana, IL", "programs_page_url": "https://cs.illinois.edu/", "type": "ai"},
    {"name": "University of Washington", "country": "USA", "city": "Seattle, WA", "programs_page_url": "https://www.cs.washington.edu/", "type": "ai"},
    {"name": "University of Pennsylvania", "country": "USA", "city": "Philadelphia, PA", "programs_page_url": "https://www.grasp.upenn.edu/", "type": "robotics"},
    {"name": "Harvard University", "country": "USA", "city": "Cambridge, MA", "programs_page_url": "https://seas.harvard.edu/", "type": "ai"},
    {"name": "Yale University", "country": "USA", "city": "New Haven, CT", "programs_page_url": "https://cpsc.yale.edu/", "type": "ai"},
    {"name": "Princeton University", "country": "USA", "city": "Princeton, NJ", "programs_page_url": "https://www.cs.princeton.edu/", "type": "ai"},
    {"name": "Columbia University", "country": "USA", "city": "New York, NY", "programs_page_url": "https://www.cs.columbia.edu/", "type": "ai"},
    {"name": "Cornell University", "country": "USA", "city": "Ithaca, NY", "programs_page_url": "https://www.cs.cornell.edu/", "type": "ai"},
    {"name": "Brown University", "country": "USA", "city": "Providence, RI", "programs_page_url": "https://cs.brown.edu/", "type": "ai"},
    {"name": "Dartmouth College", "country": "USA", "city": "Hanover, NH", "programs_page_url": "https://web.cs.dartmouth.edu/", "type": "ai"},
    {"name": "Johns Hopkins University", "country": "USA", "city": "Baltimore, MD", "programs_page_url": "https://lcsr.jhu.edu/", "type": "robotics"},
    {"name": "Northwestern University", "country": "USA", "city": "Evanston, IL", "programs_page_url": "https://www.mccormick.northwestern.edu/", "type": "robotics"},
    {"name": "University of Texas at Austin", "country": "USA", "city": "Austin, TX", "programs_page_url": "https://www.cs.utexas.edu/", "type": "ai"},
    {"name": "University of Southern California", "country": "USA", "city": "Los Angeles, CA", "programs_page_url": "https://www.usc.edu/", "type": "robotics"},
    {"name": "UCLA", "country": "USA", "city": "Los Angeles, CA", "programs_page_url": "https://www.cs.ucla.edu/", "type": "ai"},
    {"name": "UC San Diego", "country": "USA", "city": "San Diego, CA", "programs_page_url": "https://www.cs.ucsd.edu/", "type": "ai"},
    {"name": "New York University", "country": "USA", "city": "New York, NY", "programs_page_url": "https://courant.nyu.edu/", "type": "ai"},
    {"name": "Purdue University", "country": "USA", "city": "West Lafayette, IN", "programs_page_url": "https://www.cs.purdue.edu/", "type": "ai"},
    {"name": "University of Wisconsin-Madison", "country": "USA", "city": "Madison, WI", "programs_page_url": "https://www.cs.wisc.edu/", "type": "ai"},
    {"name": "UMass Amherst", "country": "USA", "city": "Amherst, MA", "programs_page_url": "https://www.cics.umass.edu/", "type": "ai"},
    {"name": "Ohio State University", "country": "USA", "city": "Columbus, OH", "programs_page_url": "https://cse.osu.edu/", "type": "ai"},
    {"name": "University of Minnesota", "country": "USA", "city": "Minneapolis, MN", "programs_page_url": "https://cse.umn.edu/", "type": "ai"},
    {"name": "Penn State University", "country": "USA", "city": "State College, PA", "programs_page_url": "https://www.eecs.psu.edu/", "type": "ai"},
    {"name": "Virginia Tech", "country": "USA", "city": "Blacksburg, VA", "programs_page_url": "https://cs.vt.edu/", "type": "ai"},
    {"name": "University of Arizona", "country": "USA", "city": "Tucson, AZ", "programs_page_url": "https://www.cs.arizona.edu/", "type": "ai"},
    {"name": "Indiana University", "country": "USA", "city": "Bloomington, IN", "programs_page_url": "https://luddy.indiana.edu/", "type": "ai"},
    {"name": "University of Pittsburgh", "country": "USA", "city": "Pittsburgh, PA", "programs_page_url": "https://www.sci.pitt.edu/", "type": "ai"},
    {"name": "Michigan State University", "country": "USA", "city": "East Lansing, MI", "programs_page_url": "https://www.cse.msu.edu/", "type": "ai"},
    {"name": "UC Irvine", "country": "USA", "city": "Irvine, CA", "programs_page_url": "https://www.cs.uci.edu/", "type": "ai"},
    {"name": "UC Davis", "country": "USA", "city": "Davis, CA", "programs_page_url": "https://cs.ucdavis.edu/", "type": "ai"},
    {"name": "UC Santa Barbara", "country": "USA", "city": "Santa Barbara, CA", "programs_page_url": "https://cs.ucsb.edu/", "type": "ai"},
    {"name": "University of Rochester", "country": "USA", "city": "Rochester, NY", "programs_page_url": "https://www.cs.rochester.edu/", "type": "ai"},
    
    # UK (50 universities)
    {"name": "University of Oxford", "country": "UK", "city": "Oxford", "programs_page_url": "https://www.ox.ac.uk/", "type": "ai"},
    {"name": "University of Cambridge", "country": "UK", "city": "Cambridge", "programs_page_url": "https://www.cam.ac.uk/", "type": "ai"},
    {"name": "Imperial College London", "country": "UK", "city": "London", "programs_page_url": "https://www.imperial.ac.uk/", "type": "robotics"},
    {"name": "UCL", "country": "UK", "city": "London", "programs_page_url": "https://www.ucl.ac.uk/", "type": "ai"},
    {"name": "University of Edinburgh", "country": "UK", "city": "Edinburgh", "programs_page_url": "https://www.ed.ac.uk/", "type": "ai"},
    {"name": "University of Manchester", "country": "UK", "city": "Manchester", "programs_page_url": "https://www.manchester.ac.uk/", "type": "robotics"},
    {"name": "University of Bristol", "country": "UK", "city": "Bristol", "programs_page_url": "https://www.bristol.ac.uk/", "type": "ai"},
    {"name": "University of Glasgow", "country": "UK", "city": "Glasgow", "programs_page_url": "https://www.gla.ac.uk/", "type": "ai"},
    {"name": "University of Warwick", "country": "UK", "city": "Coventry", "programs_page_url": "https://warwick.ac.uk/", "type": "ai"},
    {"name": "University of Southampton", "country": "UK", "city": "Southampton", "programs_page_url": "https://www.southampton.ac.uk/", "type": "ai"},
    {"name": "University of Sheffield", "country": "UK", "city": "Sheffield", "programs_page_url": "https://www.sheffield.ac.uk/", "type": "ai"},
    {"name": "University of Birmingham", "country": "UK", "city": "Birmingham", "programs_page_url": "https://www.birmingham.ac.uk/", "type": "ai"},
    {"name": "University of Leeds", "country": "UK", "city": "Leeds", "programs_page_url": "https://www.leeds.ac.uk/", "type": "ai"},
    {"name": "University of Nottingham", "country": "UK", "city": "Nottingham", "programs_page_url": "https://www.nottingham.ac.uk/", "type": "ai"},
    {"name": "University of Liverpool", "country": "UK", "city": "Liverpool", "programs_page_url": "https://www.liverpool.ac.uk/", "type": "ai"},
    {"name": "University of York", "country": "UK", "city": "York", "programs_page_url": "https://www.york.ac.uk/", "type": "ai"},
    {"name": "University of Sussex", "country": "UK", "city": "Brighton", "programs_page_url": "https://www.sussex.ac.uk/", "type": "ai"},
    {"name": "Lancaster University", "country": "UK", "city": "Lancaster", "programs_page_url": "https://www.lancaster.ac.uk/", "type": "ai"},
    {"name": "University of Surrey", "country": "UK", "city": "Guildford", "programs_page_url": "https://www.surrey.ac.uk/", "type": "ai"},
    {"name": "King's College London", "country": "UK", "city": "London", "programs_page_url": "https://www.kcl.ac.uk/", "type": "ai"},
    {"name": "Queen Mary University of London", "country": "UK", "city": "London", "programs_page_url": "https://www.qmul.ac.uk/", "type": "ai"},
    {"name": "University of Bath", "country": "UK", "city": "Bath", "programs_page_url": "https://www.bath.ac.uk/", "type": "ai"},
    {"name": "University of Exeter", "country": "UK", "city": "Exeter", "programs_page_url": "https://www.exeter.ac.uk/", "type": "ai"},
    {"name": "Cardiff University", "country": "UK", "city": "Cardiff", "programs_page_url": "https://www.cardiff.ac.uk/", "type": "ai"},
    {"name": "University of Aberdeen", "country": "UK", "city": "Aberdeen", "programs_page_url": "https://www.abdn.ac.uk/", "type": "ai"},
    {"name": "University of Dundee", "country": "UK", "city": "Dundee", "programs_page_url": "https://www.dundee.ac.uk/", "type": "ai"},
    {"name": "University of Strathclyde", "country": "UK", "city": "Glasgow", "programs_page_url": "https://www.strath.ac.uk/", "type": "ai"},
    {"name": "Swansea University", "country": "UK", "city": "Swansea", "programs_page_url": "https://www.swansea.ac.uk/", "type": "ai"},
    {"name": "University of Portsmouth", "country": "UK", "city": "Portsmouth", "programs_page_url": "https://www.port.ac.uk/", "type": "ai"},
    {"name": "University of Reading", "country": "UK", "city": "Reading", "programs_page_url": "https://www.reading.ac.uk/", "type": "ai"},
    {"name": "University of Leicester", "country": "UK", "city": "Leicester", "programs_page_url": "https://le.ac.uk/", "type": "ai"},
    {"name": "University of Essex", "country": "UK", "city": "Colchester", "programs_page_url": "https://www.essex.ac.uk/", "type": "ai"},
    {"name": "University of East Anglia", "country": "UK", "city": "Norwich", "programs_page_url": "https://www.uea.ac.uk/", "type": "ai"},
    {"name": "City, University of London", "country": "UK", "city": "London", "programs_page_url": "https://www.city.ac.uk/", "type": "ai"},
    {"name": "Brunel University London", "country": "UK", "city": "London", "programs_page_url": "https://www.brunel.ac.uk/", "type": "ai"},
    {"name": "Loughborough University", "country": "UK", "city": "Loughborough", "programs_page_url": "https://www.lboro.ac.uk/", "type": "ai"},
    {"name": "University of Plymouth", "country": "UK", "city": "Plymouth", "programs_page_url": "https://www.plymouth.ac.uk/", "type": "ai"},
    {"name": "University of Hull", "country": "UK", "city": "Hull", "programs_page_url": "https://www.hull.ac.uk/", "type": "ai"},
    {"name": "University of Salford", "country": "UK", "city": "Salford", "programs_page_url": "https://www.salford.ac.uk/", "type": "ai"},
    {"name": "University of Westminster", "country": "UK", "city": "London", "programs_page_url": "https://www.westminster.ac.uk/", "type": "ai"},
    {"name": "University of Greenwich", "country": "UK", "city": "London", "programs_page_url": "https://www.gre.ac.uk/", "type": "ai"},
    {"name": "University of Hertfordshire", "country": "UK", "city": "Hatfield", "programs_page_url": "https://www.herts.ac.uk/", "type": "ai"},
    {"name": "University of Derby", "country": "UK", "city": "Derby", "programs_page_url": "https://www.derby.ac.uk/", "type": "ai"},
    {"name": "University of Lincoln", "country": "UK", "city": "Lincoln", "programs_page_url": "https://www.lincoln.ac.uk/", "type": "ai"},
    {"name": "University of Chester", "country": "UK", "city": "Chester", "programs_page_url": "https://www1.chester.ac.uk/", "type": "ai"},
    {"name": "University of Bolton", "country": "UK", "city": "Bolton", "programs_page_url": "https://www.bolton.ac.uk/", "type": "ai"},
    {"name": "University of the West of Scotland", "country": "UK", "city": "Paisley", "programs_page_url": "https://www.uws.ac.uk/", "type": "ai"},
    {"name": "University of Wales Trinity Saint David", "country": "UK", "city": "Lampeter", "programs_page_url": "https://www.uwtsd.ac.uk/", "type": "ai"},
    {"name": "Buckinghamshire New University", "country": "UK", "city": "High Wycombe", "programs_page_url": "https://www.bucks.ac.uk/", "type": "ai"},
    {"name": "London Metropolitan University", "country": "UK", "city": "London", "programs_page_url": "https://www.londonmet.ac.uk/", "type": "ai"},
    
    # Germany (17)
    {"name": "Technical University of Munich", "country": "Germany", "city": "Munich", "programs_page_url": "https://www.tum.de/", "type": "both"},
    {"name": "RWTH Aachen", "country": "Germany", "city": "Aachen", "programs_page_url": "https://www.rwth-aachen.de/", "type": "robotics"},
    {"name": "Karlsruhe Institute of Technology", "country": "Germany", "city": "Karlsruhe", "programs_page_url": "https://www.kit.edu/", "type": "robotics"},
    {"name": "TU Berlin", "country": "Germany", "city": "Berlin", "programs_page_url": "https://www.tu.berlin/", "type": "robotics"},
    {"name": "University of Stuttgart", "country": "Germany", "city": "Stuttgart", "programs_page_url": "https://www.uni-stuttgart.de/", "type": "robotics"},
    {"name": "TU Dresden", "country": "Germany", "city": "Dresden", "programs_page_url": "https://tu-dresden.de/", "type": "robotics"},
    {"name": "University of Freiburg", "country": "Germany", "city": "Freiburg", "programs_page_url": "https://www.uni-freiburg.de/", "type": "ai"},
    {"name": "University of Tübingen", "country": "Germany", "city": "Tübingen", "programs_page_url": "https://www.uni-tuebingen.de/", "type": "ai"},
    {"name": "LMU Munich", "country": "Germany", "city": "Munich", "programs_page_url": "https://www.lmu.de/", "type": "ai"},
    {"name": "Heidelberg University", "country": "Germany", "city": "Heidelberg", "programs_page_url": "https://www.uni-heidelberg.de/", "type": "ai"},
    {"name": "Saarland University", "country": "Germany", "city": "Saarbrücken", "programs_page_url": "https://www.uni-saarland.de/", "type": "ai"},
    {"name": "University of Bonn", "country": "Germany", "city": "Bonn", "programs_page_url": "https://www.uni-bonn.de/", "type": "ai"},
    {"name": "TU Darmstadt", "country": "Germany", "city": "Darmstadt", "programs_page_url": "https://www.tu-darmstadt.de/", "type": "robotics"},
    {"name": "University of Hamburg", "country": "Germany", "city": "Hamburg", "programs_page_url": "https://www.uni-hamburg.de/", "type": "ai"},
    {"name": "FAU Erlangen-Nuremberg", "country": "Germany", "city": "Erlangen", "programs_page_url": "https://www.fau.de/", "type": "ai"},
    {"name": "University of Mannheim", "country": "Germany", "city": "Mannheim", "programs_page_url": "https://www.uni-mannheim.de/", "type": "ai"},
    {"name": "Jacobs University", "country": "Germany", "city": "Bremen", "programs_page_url": "https://www.jacobs-university.de/", "type": "ai"},
    
    # Spain (20)
    {"name": "UPC Barcelona", "country": "Spain", "city": "Barcelona", "programs_page_url": "https://www.upc.edu/", "type": "robotics"},
    {"name": "UPM Madrid", "country": "Spain", "city": "Madrid", "programs_page_url": "https://www.upm.es/", "type": "robotics"},
    {"name": "University of Barcelona", "country": "Spain", "city": "Barcelona", "programs_page_url": "https://www.ub.edu/", "type": "ai"},
    {"name": "UAM Madrid", "country": "Spain", "city": "Madrid", "programs_page_url": "https://www.uam.es/", "type": "ai"},
    {"name": "UCM Madrid", "country": "Spain", "city": "Madrid", "programs_page_url": "https://www.ucm.es/", "type": "ai"},
    {"name": "UC3M Madrid", "country": "Spain", "city": "Madrid", "programs_page_url": "https://www.uc3m.es/", "type": "ai"},
    {"name": "University of Granada", "country": "Spain", "city": "Granada", "programs_page_url": "https://www.ugr.es/", "type": "ai"},
    {"name": "UPF Barcelona", "country": "Spain", "city": "Barcelona", "programs_page_url": "https://www.upf.edu/", "type": "ai"},
    {"name": "University of Malaga", "country": "Spain", "city": "Malaga", "programs_page_url": "https://www.uma.es/", "type": "ai"},
    {"name": "University of Seville", "country": "Spain", "city": "Seville", "programs_page_url": "https://www.us.es/", "type": "ai"},
    {"name": "University of Zaragoza", "country": "Spain", "city": "Zaragoza", "programs_page_url": "https://www.unizar.es/", "type": "ai"},
    {"name": "University of Valladolid", "country": "Spain", "city": "Valladolid", "programs_page_url": "https://www.uva.es/", "type": "ai"},
    {"name": "University of Girona", "country": "Spain", "city": "Girona", "programs_page_url": "https://www.udg.edu/", "type": "robotics"},
    {"name": "University of Alcalá", "country": "Spain", "city": "Alcalá", "programs_page_url": "https://www.uah.es/", "type": "ai"},
    {"name": "University of Deusto", "country": "Spain", "city": "Bilbao", "programs_page_url": "https://www.deusto.es/", "type": "ai"},
    {"name": "University of Navarra", "country": "Spain", "city": "Pamplona", "programs_page_url": "https://www.unav.edu/", "type": "ai"},
    {"name": "URJC Madrid", "country": "Spain", "city": "Madrid", "programs_page_url": "https://www.urjc.es/", "type": "ai"},
    {"name": "UCLM Spain", "country": "Spain", "city": "Ciudad Real", "programs_page_url": "https://www.uclm.es/", "type": "ai"},
    {"name": "University of Alicante", "country": "Spain", "city": "Alicante", "programs_page_url": "https://www.ua.es/", "type": "ai"},
    {"name": "University of Valencia", "country": "Spain", "city": "Valencia", "programs_page_url": "https://www.uv.es/", "type": "ai"},
    
    # Austria (10)
    {"name": "TU Wien", "country": "Austria", "city": "Vienna", "programs_page_url": "https://www.tuwien.at/", "type": "robotics"},
    {"name": "JKU Linz", "country": "Austria", "city": "Linz", "programs_page_url": "https://www.jku.at/", "type": "ai"},
    {"name": "University of Klagenfurt", "country": "Austria", "city": "Klagenfurt", "programs_page_url": "https://www.aau.at/", "type": "ai"},
    {"name": "TU Graz", "country": "Austria", "city": "Graz", "programs_page_url": "https://www.tugraz.at/", "type": "ai"},
    {"name": "University of Vienna", "country": "Austria", "city": "Vienna", "programs_page_url": "https://www.univie.ac.at/", "type": "ai"},
    {"name": "FH JOANNEUM", "country": "Austria", "city": "Graz", "programs_page_url": "https://www.fh-joanneum.at/", "type": "ai"},
    {"name": "FH Salzburg", "country": "Austria", "city": "Salzburg", "programs_page_url": "https://www.fh-salzburg.ac.at/", "type": "ai"},
    {"name": "University of Innsbruck", "country": "Austria", "city": "Innsbruck", "programs_page_url": "https://www.uibk.ac.at/", "type": "robotics"},
    {"name": "FH Technikum Wien", "country": "Austria", "city": "Vienna", "programs_page_url": "https://www.technikum-wien.at/", "type": "robotics"},
    {"name": "FH Upper Austria", "country": "Austria", "city": "Hagenberg", "programs_page_url": "https://www.fh-ooe.at/", "type": "ai"},
    
    # Italy (15)
    {"name": "Politecnico di Milano", "country": "Italy", "city": "Milan", "programs_page_url": "https://www.polimi.it/", "type": "both"},
    {"name": "University of Bologna", "country": "Italy", "city": "Bologna", "programs_page_url": "https://www.unibo.it/", "type": "ai"},
    {"name": "Sapienza University of Rome", "country": "Italy", "city": "Rome", "programs_page_url": "https://www.uniroma1.it/", "type": "both"},
    {"name": "University of Trento", "country": "Italy", "city": "Trento", "programs_page_url": "https://www.unitn.it/", "type": "ai"},
    {"name": "Politecnico di Torino", "country": "Italy", "city": "Turin", "programs_page_url": "https://www.polito.it/", "type": "robotics"},
    {"name": "University of Genova", "country": "Italy", "city": "Genova", "programs_page_url": "https://www.unige.it/", "type": "robotics"},
    {"name": "University of Padova", "country": "Italy", "city": "Padova", "programs_page_url": "https://www.unipd.it/", "type": "robotics"},
    {"name": "Scuola Superiore Sant'Anna", "country": "Italy", "city": "Pisa", "programs_page_url": "https://www.santannapisa.it/", "type": "robotics"},
    {"name": "University of Pisa", "country": "Italy", "city": "Pisa", "programs_page_url": "https://www.unipi.it/", "type": "robotics"},
    {"name": "Bocconi University", "country": "Italy", "city": "Milan", "programs_page_url": "https://www.unibocconi.eu/", "type": "ai"},
    {"name": "Università Cattolica", "country": "Italy", "city": "Milan", "programs_page_url": "https://www.unicatt.it/", "type": "ai"},
    {"name": "University of Florence", "country": "Italy", "city": "Florence", "programs_page_url": "https://www.unifi.it/", "type": "ai"},
    {"name": "University of Naples", "country": "Italy", "city": "Naples", "programs_page_url": "https://www.unina.it/", "type": "ai"},
    {"name": "University of Calabria", "country": "Italy", "city": "Cosenza", "programs_page_url": "https://www.unical.it/", "type": "robotics"},
    {"name": "University of Milan-Bicocca", "country": "Italy", "city": "Milan", "programs_page_url": "https://www.unimib.it/", "type": "ai"},
    
    # Sweden (1)
    {"name": "KTH Royal Institute", "country": "Sweden", "city": "Stockholm", "programs_page_url": "https://www.kth.se/", "type": "robotics"},
]

# Currency conversion rates to USD (approximate)
FX_RATES = {
    "USD": 1.0,
    "EUR": 1.09,
    "GBP": 1.27,
    "CHF": 1.14,
    "SEK": 0.095,
    "NOK": 0.093,
    "DKK": 0.146,
    "SGD": 0.75,
    "CAD": 0.74,
    "AUD": 0.66,
    "JPY": 0.0067,
    "KRW": 0.00076
}

def get_seeds_by_country(country: str = None):
    """Get seeds filtered by country."""
    if country:
        return [s for s in UNIVERSITY_SEEDS if s['country'].lower() == country.lower()]
    return UNIVERSITY_SEEDS

def get_seeds_by_type(type_filter: str = None):
    """Get seeds filtered by type (robotics, ai, both)."""
    if type_filter:
        return [s for s in UNIVERSITY_SEEDS if s['type'] == type_filter or s['type'] == 'both']
    return UNIVERSITY_SEEDS
